### ISSUE TITLE
Return almond.js as string when required from node.js

### ISSUE THREAD

**Issue by zanona** [jrburke/almond#102]
I am implementing a solution where It's possible to automatically inject almond as a replacement for requirejs through r.js's  optimize `rawText` attribute by having the following call:

```js
requirejs.optimize({
  baseUrl: process.env.VENDOR_PATH,
  name: 'almond',
  include: ['main'],
  insertRequire: ['main'],
  rawText: {
    'almond': fs.readFileSync(require.resolve('almond')).toString(),
    'main': dataFromMain
  },
});
```

However as it's possible to see, there is a slight process to be done before retrieving contents for `almond.js` which in my module's dependency list.
Considering this, I would like to suggest that when required through node.js, almond returned its string content instead? —Currently `require('almond')` results in `{}`.

**Comment by jrburke** [comment]
almond is not designed to be a node module, and I think it is fairly non-standard for a node module to just return the text of itself. I would prefer to not do this. 

You could set a requirejs paths config in that object passed to reuqirejs.optimize() for 'almond', and the value I think would just be `require.resolve('almond')`, and then the optimizer will do the text work for you.

**Comment by zanona** [comment]
Thanks, I will try that instead. I was just wondering that the reason for almond being available through npm could have something to do with a way to use it through nodejs for automation.
