### ISSUE TITLE
can't get requirejs, angularjs and almond to work together

### ISSUE THREAD

**Issue by PedroEsperanca** [jrburke/almond#108]
http://stackoverflow.com/questions/29056152/cant-get-requirejs-angularjs-and-almond-to-work-together

**Comment by ooxi** [comment]
Please post complete bug reports and not just a link to an external site. Moreover according to http://stackoverflow.com/a/29085895 you did solve the problem. Please update this bug report accordingly.

**Comment by PedroEsperanca** [comment]
sorry!! I totally forgot
