### ISSUE TITLE
AlmondJS + CDN module with UMD

### ISSUE THREAD

**Issue by bjnsn** [jrburke/almond#112]
Recently ran into a collision between a built version of a project that uses AlmondJS but loads a CDN version of [webfontloader](https://github.com/typekit/webfontloader/). Webfontloader recently [added a UMD wrapper](https://github.com/typekit/webfontloader/commit/68a176234797fd90b42054e56e6adbeb6a0ef319) - and that caused an error within the AlmondJS `define` method:  

      Uncaught TypeError: Cannot read property 'splice' of undefined

The culprit was a call within [the webfontloader UMD wrapper](https://github.com/typekit/webfontloader/commit/68a176234797fd90b42054e56e6adbeb6a0ef319) with this signature: `define(function():*)`. This is valid within RequireJS, but isn't within AlmondJS.

Is this an issue with Webfontloader, with AlmondJS - or should I not be running AlmondJS alongside CDN versions of libraries that use UMD?

**Comment by jrburke** [comment]
Almond is [not designed to load remote resources](https://github.com/jrburke/almond#restrictions), it is strictly for use when combining a bunch of modules into one file for download. So this behavior is expected, out of scope for almond.

**Comment by bjnsn** [comment]
Hmm. I'm not using it to load an external resource; it is being referenced by an external resource that is already loaded via a script tag (from a CDN). Almond's `define` is being duck-typed by Webontloader's UMD wrapper to see if it is an AMD loader - once it is decided that it 'quacks like a duck' it proceeds to use it like RequireJS `define`. 

I believe a **noConflict** option that would prevent AlmondJS from injecting `define` into the global scope would solve the issue. That way other files on the page which check for `define` wouldn't find one that doesn't behave as expected.

**Comment by jrburke** [comment]
You can get the effect of a noConflict by building with the r.js optimizer setting [wrap: true](https://github.com/jrburke/r.js/blob/5cd88c87839b3c2e72d872a90436f0270d611fd0/build/example.build.js#L476).

**Comment by bjnsn** [comment]
Perfect - exactly what I was looking for!
