### ISSUE TITLE
Any way to listen the DOMContentLoaded event

### ISSUE THREAD

**Issue by IEfucker** [jrburke/almond#113]
Window's load event can be listened, but the DOMContentLoaded event can not.

`document.addEventListener('DOMContentLoaded', function(e){
        console.log("DOMContentLoaded");
    },false);`

Is that not supported?

**Comment by jrburke** [comment]
Depending on when the script that includes almond and the bundled modules is loaded (like if it is in a script defer tag) the DOMContentLoaded event may have already passed. Testing for document.readyState in addition to setting the DOMContentLoaded event might help, but [there are some funky complications across browsers](https://github.com/requirejs/domReady/blob/c74caaa6dac64f2f47093f4952b991390406adfb/domReady.js#L81). Best to also register a window load event too.

Closing as a discussion ticket, feel free to continue discussion here.
