### ISSUE TITLE
Almong not run deps for require.config

### ISSUE THREAD

**Issue by MikeBazhenov** [jrburke/almond#93]
Hi!

When i build app, app not run module `boot` declared in `require.config`

```
.pipe(rjs({
            mainConfigFile: './public/js/requirejs.config.js',
            name: '../vendors/almond/almond',
            baseUrl: './public/js',
            out: 'out.js',
            removeCombined: true,
            findNestedDependencies: true
        }))
```

//requirejs.config.js

```
require.config({
    baseUrl: "/js",
    waitSeconds: 60,
    paths: {
        ...
    },
    urlArgs: "v=1.5",
    shim: {
        ...
    },
    deps: ["boot"]
});
```

//boot.js
```
define([
   ...
],
    function ($, angular) {
        'use strict';
        console.log('boot');
        $(document).ready(function () {
            angular.bootstrap(document, ['app']);
        });
    });
```

**Comment by jrburke** [comment]
The requirejs.config.js file needs to be included in the built output. This can be done by changing the 'name' config to point to requirejs.config, and then use the [include](https://github.com/jrburke/r.js/blob/47adf0a236d11e393aa5869809eca4b55060f1f2/build/example.build.js#L381) build option to include almond.

Going to close as I believe that is the source of the issue.
